## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Roros,NO,62.5747,11.3842,46.24,93,75,3.44,light rain
1,1,Avera,US,33.1940,-82.5271,86.05,64,94,7.67,overcast clouds
2,2,Bluff,NZ,-46.6000,168.3333,47.80,73,99,21.81,overcast clouds
3,3,General Pico,AR,-35.6566,-63.7568,44.08,70,36,6.08,scattered clouds
4,4,San Juan Ixcoy,GT,15.5997,-91.4453,59.85,94,100,5.01,overcast clouds
5,5,Narsaq,GL,60.9167,-46.0500,41.22,68,2,1.03,clear sky
6,6,Punta Arenas,CL,-53.1500,-70.9167,42.91,56,75,9.22,broken clouds
7,7,Villa Carlos Paz,AR,-31.4241,-64.4978,47.39,44,100,3.02,overcast clouds
8,8,Arraial Do Cabo,BR,-22.9661,-42.0278,62.46,88,40,5.75,scattered clouds
9,9,Champerico,GT,14.3000,-91.9167,78.96,83,98,8.05,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Avera,US,33.1940,-82.5271,86.05,64,94,7.67,overcast clouds
9,9,Champerico,GT,14.3000,-91.9167,78.96,83,98,8.05,overcast clouds
11,11,Kahului,US,20.8947,-156.4700,82.42,74,0,20.71,clear sky
13,13,Bathsheba,BB,13.2167,-59.5167,83.01,83,40,19.57,scattered clouds
17,17,Dingle,PH,10.9995,122.6711,87.89,65,75,6.87,broken clouds
21,21,Kapaa,US,22.0752,-159.3190,82.38,84,75,17.27,broken clouds
25,25,Chifeng,CN,42.2683,118.9636,80.82,30,9,1.68,clear sky
31,31,Hovd,MN,48.0056,91.6419,75.72,25,59,4.14,light rain
36,36,Sisophon,KH,13.5859,102.9737,87.71,58,100,4.03,overcast clouds
37,37,Kavaratti,IN,10.5669,72.6420,83.30,75,100,14.88,moderate rain

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                236
City                   236
Country                236
Lat                    236
Lng                    236
Max Temp               236
Humidity               236
Cloudiness             236
Wind Speed             236
Current Description    236
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Avera,US,33.1940,-82.5271,86.05,64,94,7.67,overcast clouds
9,9,Champerico,GT,14.3000,-91.9167,78.96,83,98,8.05,overcast clouds
11,11,Kahului,US,20.8947,-156.4700,82.42,74,0,20.71,clear sky
13,13,Bathsheba,BB,13.2167,-59.5167,83.01,83,40,19.57,scattered clouds
17,17,Dingle,PH,10.9995,122.6711,87.89,65,75,6.87,broken clouds
...,...,...,...,...,...,...,...,...,...,...
706,706,Agadez,NE,19.7500,10.2500,85.73,32,100,8.93,overcast clouds
707,707,Moratuwa,LK,6.7730,79.8816,78.82,83,100,6.42,moderate rain
708,708,Fare,PF,-16.7000,-151.0167,80.47,71,2,16.26,clear sky
711,711,Tucumcari,US,35.1717,-103.7250,89.44,18,0,11.50,clear sky
712,712,Kuliyapitiya,LK,7.4688,80.0401,78.48,77,99,5.84,overcast clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Avera,US,86.05,overcast clouds,33.1940,-82.5271,
9,Champerico,GT,78.96,overcast clouds,14.3000,-91.9167,
11,Kahului,US,82.42,clear sky,20.8947,-156.4700,
13,Bathsheba,BB,83.01,scattered clouds,13.2167,-59.5167,
17,Dingle,PH,87.89,broken clouds,10.9995,122.6711,
21,Kapaa,US,82.38,broken clouds,22.0752,-159.3190,
25,Chifeng,CN,80.82,clear sky,42.2683,118.9636,
31,Hovd,MN,75.72,light rain,48.0056,91.6419,
36,Sisophon,KH,87.71,overcast clouds,13.5859,102.9737,
37,Kavaratti,IN,83.30,moderate rain,10.5669,72.6420,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # 6c. Get latitude and longitude from DataFrame
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

ConnectionError: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/place/nearbysearch/json?radius=5000&type=lodging&key=AIzaSyB-Xw_t0XKqfFkO0pVmJq8nNqDETGur88M&location=33.194%2C-82.5271 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021AF1D28D48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

In [ ]:
# 7. Drop the rows where there is no Hotel Name.

In [ ]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure